In [1]:
import pandas as pd 
from sklearn.model_selection import train_test_split

In [2]:
df=pd.read_csv('iris.csv')

In [3]:
df

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [4]:
# df=df.drop("Id",axis=1)
X = df.drop("variety", axis = 1)
y = df["variety"]
print('Shape of X = ', X.shape)
print('Shape of y = ', y.shape)

Shape of X =  (150, 4)
Shape of y =  (150,)


In [5]:
d={'Setosa':0,'Versicolor':1, 'Virginica':2}
df["variety"]=df["variety"].map(d)
y = df["variety"]
print (y)

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: variety, Length: 150, dtype: int64


In [6]:
X_train, X_test, y_train, y_test =train_test_split(X, y, test_size=0.2, random_state=51)
print('Shape of X_train = ', X_train.shape)
print('Shape of y_train = ', y_train.shape)
print('Shape of X_test = ', X_test.shape)
print('Shape of y_test = ', y_test.shape)

Shape of X_train =  (120, 4)
Shape of y_train =  (120,)
Shape of X_test =  (30, 4)
Shape of y_test =  (30,)


In [7]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [8]:
sc = StandardScaler()
sc.fit(X_train)
X_train_sc = sc.transform(X_train)
X_test_sc = sc.transform(X_test)

In [9]:
# Feature Test Data, non-standardized
X_test[0:5]

sepal.length  sepal.width  petal.length  petal.width
78            6.0          2.9           4.5          1.5
121           5.6          2.8           4.9          2.0
99            5.7          2.8           4.1          1.3
36            5.5          3.5           1.3          0.2
92            5.8          2.6           4.0          1.2

In [10]:
# Feature Test Data, standardized.
X_test_sc[0:5]

array([[ 0.26596461, -0.30399027,  0.4761495 ,  0.46952732],
       [-0.21944608, -0.54398259,  0.70747719,  1.14028065],
       [-0.09809341, -0.54398259,  0.24482181,  0.201226  ],
       [-0.34079876,  1.13596365, -1.37447204, -1.27443131],
       [ 0.02325926, -1.02396723,  0.18698988,  0.06707533]])

In [11]:
X_train_sc =  pd.DataFrame(X_train_sc, columns = ["SepalLengthCm",'SepalWidthCm','PetalLengthCm','PetalWidthCm'])
X_test_sc =  pd.DataFrame(X_test_sc, columns = ["SepalLengthCm",'SepalWidthCm','PetalLengthCm','PetalWidthCm'])

In [12]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

In [13]:
pred=clf.predict(X_test)
print (pred)
clf.score(X_test,y_test)

[1 2 1 0 1 2 2 2 0 2 2 0 1 2 2 2 1 2 2 0 2 2 0 0 1 2 0 0 0 2]


0.9333333333333333

In [16]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report 
print ("Accuracy : " , accuracy_score(y_test,pred)*100)  
print("Report : \n", classification_report(y_test, pred))
print("F1 Score : ",f1_score(y_test, pred, average='macro')*100)

Accuracy :  93.33333333333333
Report : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       0.83      0.83      0.83         6
           2       0.93      0.93      0.93        15

    accuracy                           0.93        30
   macro avg       0.92      0.92      0.92        30
weighted avg       0.93      0.93      0.93        30

F1 Score :  92.22222222222221


In [13]:
from sklearn.neighbors import KNeighborsClassifier
# clf1=KNeighborsClassifier()
# clf1.fit(X_train, y_train)
# pred=clf1.predict(X_test)
# clf1.score(X_test,y_test)

In [20]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report 
print ("Accuracy : " , accuracy_score(y_test,pred)*100)  
print("Report : \n", classification_report(y_test, pred))
print("F1 Score : ",f1_score(y_test, pred, average='macro')*100)

Accuracy :  96.66666666666667
Report : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       0.86      1.00      0.92         6
           2       1.00      0.93      0.97        15

    accuracy                           0.97        30
   macro avg       0.95      0.98      0.96        30
weighted avg       0.97      0.97      0.97        30

F1 Score :  96.28647214854111


In [14]:
clf1=KNeighborsClassifier()
clf1.fit(X_train_sc,y_train)
pred=clf1.predict(X_test_sc)
clf1.score(X_test_sc,y_test)

0.9333333333333333

In [40]:
from sklearn.decomposition import PCA

pca=PCA(n_components=3)
X_trainn=pca.fit_transform(X_train_sc)
X_testt=pca.transform(X_test_sc)

In [41]:
ex=pca.explained_variance_ratio_
ex

array([0.74173795, 0.21963139, 0.03368146])

In [42]:
clf1=KNeighborsClassifier()
clf1.fit(X_trainn,y_train)
pred=clf1.predict(X_testt)
clf1.score(X_testt,y_test)

0.9666666666666667