In [2]:
import numpy as np

In [ ]:
# %timeit [i+1 for i in range(900000000)]

In [3]:
# %timeit np.arange(900000000)+1

2.64 ms ± 42.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [3]:
n=np.array([1,2,3,4])
n

array([1, 2, 3, 4])

In [5]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
type(b)

numpy.ndarray

In [6]:
l=[1,2,3,4]
p=np.array(l)
p

array([1, 2, 3, 4])

In [8]:
k=np.linspace(1,10,4)
print(k)

[ 1.  4.  7. 10.]


In [9]:
y=np.loadtxt("file.txt",delimiter="and")
print(y)

[1. 2. 3.]


In [10]:
s=np.empty((3,3))
s

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 5.51377261e-321],
       [1.05699242e-307, 8.01097888e-307, 2.80103444e-312]])

In [22]:
import numpy as np
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [7]:
print (a[0])
print (a[4])

1
5


In [8]:
a[[0,4]]

array([1, 5])

In [20]:
a
a=[1,2,3,4,5,6]

In [21]:
b=[]
for i in a:
    if(i%2!=0):
        b.append(0)
    else:
        b.append(i)
print (b)    

[0, 2, 0, 4, 0, 6]


In [23]:
# k=a%2==0
# k
# print (a[k])

a[a%2!=0]=0
print (a)


# b=a%2==0
# a[a%2!=0]=0
# print(b)
# print(a[b])
# print(a)

[0 2 0 4 0 6]


In [30]:
a=np.array([1,2,3,10,5,6],np.int8)
print(a)

[ 1  2  3 10  5  6]


In [31]:
a.shape

(6,)

In [32]:
a.ndim

1

In [33]:
a.dtype

dtype('int8')

In [34]:
a.size

6

In [35]:
a.nbytes

6

In [37]:
a.argmax()

3

In [38]:
a.argmin()

0

In [39]:
a.argsort()

array([0, 1, 2, 4, 5, 3], dtype=int64)